server:
  port: 9009
spring:
  application:
    name: sentinel-gateway-9009
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: ${spring.application.name}
    gateway:
      #      default-filters:
      #        - AddRequestHeader=token,sentinel-gateway-9009
      #global http timeouts
      httpclient:
        # default is 45s
        connect-timeout: 10000
        response-timeout: 5s
      #        wiretap: true
      #      httpserver:
      #        wiretap: true
      #从 1.6.0 版本开始，Sentinel 提供了 Spring Cloud Gateway 的适配模块，可以提供两种资源维度的限流：
      #route 维度：即在 Spring 配置文件中配置的路由条目，资源名为对应的 routeId
      #自定义 API 维度：用户可以利用 Sentinel 提供的 API 来自定义一些 API 分组
      routes:
        - id: gateway-nacos-provider-9005
          uri: http://127.0.0.1:9005
          predicates:
            - Path=/nacos-provider-9005/**
          filters:
            - AddRequestHeader=nacos-provider,nacosProvider9005
        - id: gateway-nacos-consumer-9006
          uri: http://127.0.0.1:9006
          predicates:
            - Path=/nacos-consumer-9006/**
          metadata:
            testMetadata: zhuweiwei
            optionName: zww
            # Per-route http timeouts
            response-timeout: 1000
            connect-timeout: 3000
        - id: gateway-sentinel-provider-9007
          uri: http://127.0.0.1:9007
          predicates:
            - Path=/sentinel-provider-9007/**
        - id: gateway-sentinel-consumer-9017
          uri: http://127.0.0.1:9017
          predicates:
            - Path=/sentinel-consumer-9017/**
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080
          #gateway整合sentinel Dynamic Data Source Support sentinel配置存储在动态数据源
      datasource:
        #以下暂未测试通过？？？
        #网关流量控制
        flow:
          nacos:
            serverAddr: 127.0.0.1:8848
            groupId: nacos-datasource-config
            dataId: ${spring.application.name}-gw-flow
            dataType: json
            ruleType: gw-flow
          #熔断降级
          degrade:
            nacos:
              serverAddr: 127.0.0.1:8848
              groupId: nacos-datasource-config
              dataId: ${spring.application.name}-degrade
              dataType: json
              ruleType: degrade
#Endpoint 支持
management:
  endpoints:
    web:
      exposure:
        include: '*'
#        include: gateway
logging:
  file:
    name: gateway-log.log
    max-size: 100MB
    max-history: 30
#  level:
#    reactor:
#      netty: debug
