server:
  port: 9003
  servlet:
    context-path: /consul-provider
spring:
  application:
    name: consul-provider-9003
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}